[package]
name = "hash-bench"
version = "0.1.0"
authors = ["toshipp <toshiq2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnv = "1.0.6"
siphasher = "0.3.1"
fxhash = "0.2.1"
